services:
  - type: web
    name: resumeai-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: MONGO_URI
        value: mongodb://sakethgudapati_db_user:dNIJcyzIYxTfRs5L@ac-szwjtv3-shard-00-00.qu6jdhv.mongodb.net:27017,ac-szwjtv3-shard-00-01.qu6jdhv.mongodb.net:27017,ac-szwjtv3-shard-00-02.qu6jdhv.mongodb.net:27017/?authSource=admin&replicaSet=atlas-txiz5x-shard-0&tls=true
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false

  - type: web
    name: resumeai-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    headers:
      - path: /*
        headers:
          - key: Cache-Control
            value: public, max-age=31536000, immutable
    envVars:
      - key: VITE_API_URL
        value: https://resumeai-backend.onrender.com